<?php

namespace AppBundle\Repository;

/**
 * authorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class authorRepository extends \Doctrine\ORM\EntityRepository
{
}
